### PR TITLE
Update fastlane-plugin-xml_editor.gemspec

### PR DESCRIPTION
**Pull request by ssanabriacec**
nokogiri version upgraded

@ustudio/reviewers please review

### CODE REVIEW

**Comment by tjensen** [comment]
@ssanabriacec Should we get this repo set up to build in CircleCI? I see that there is already a (unsupported) v1 `circle.yml` configuration file, so we could upgrade to a v2 config and run the unit tests in CI.

**Comment by ssanabriacec** [comment]
@tjensen I actually don't know, I will check it, I've never done this but I'll see what I can do, I'll ask if I have questions

**Comment by ssanabriacec** [comment]
@tjensen as discussed, we removed the rake call on the new `config.yml` and just run the `bundle install`. We added a call to `rubocop` but it throws a bunch of warnings so it was removed.

Also upgraded the version from `0.2.0` to `0.2.1` to make differentiate it from the original repo and a later tag I have to add.

**Review by tjensen — APPROVED** [review]
@ssanabriacec LGTM. Sorry for sending you down the CircleCI path when it turned out not to be as fruitful as we'd hoped.

**Pull request merged**
